# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano//zmk" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano//zmk
#     shield: reviung41
#
---
include:
  - board: nice_nano//zmk
    shield: corne_left
    snippet: studio-rpc-usb-uart
    artifact-name: left-corne-studio
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano//zmk
    shield: corne_left
    # snippet: zmk-usb-logging
    artifact-name: left-corne-logging
  - board: nice_nano//zmk
    shield: corne_right
    snippet: zmk-usb-logging
    artifact-name: right-corne-logging
  - board: nice_nano//zmk
    shield: settings_reset
  # - board: nice_nano//zmk
  #   shield: corne_tp_left
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: left-corne-tp-studio
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano//zmk
    shield: corne_tp_left
    # snippet: zmk-usb-logging
    artifact-name: left-corne-tp
  - board: nice_nano//zmk
    shield: corne_tp_right
    snippet: zmk-usb-logging
    artifact-name: right-corne-tp-logging
  - board: nice_nano//zmk
    shield: corne_tp_right
    artifact-name: right-corne-tp
    snippet: cdc-acm-console
