manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: saiskee
      url-base: https://github.com/saiskee
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      # remote: saiskee # small movement detector
      remote: infused-kim
      revision: corne-tp-listener
  self:
    path: config
